version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Customize port as needed
    environment:
      - PYTHONUNBUFFERED=1
      # Add your environment variables here
      # - DATABASE_URL=postgresql://user:pass@db:5432/mydb
    # volumes:
      # Optional: Mount volumes for persistent data
      # - ./data:/app/data:ro
      # - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    # depends_on:
    #   - db  # Uncomment if you need a database

  # Example database service (uncomment and customize as needed)
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# volumes:
#   postgres_data:
